### ISSUE TITLE
Doesnt retrieve FirebaseAuth Otps

### ISSUE THREAD

**Issue by shouryalala** [jaumard/sms_autofill#10]
Hi,

I'm using Firebase for authentication and it doesnt push notifications in the exact way you mentioned in the requirements. 
Is there a workaround to picking up the code automatically?

**Comment by jaumard** [comment]
Hello, 

No there is no other way, but Firebase Auth is already retrieving the sms code automatically (you just don't have the widget but you can use this one https://github.com/TinoGuo/pin_input_text_field)

**Comment by chiragmittal19** [comment]
@shouryalala Did you find any solution to that? There is no way to change the format of FirebaseAuth SMS.
