### ISSUE TITLE
Run a function on completing PhoneFieldHint

### ISSUE THREAD

**Issue by prodosdigital** [jaumard/sms_autofill#100]
Hello,
is there any way we can automatically run a function as soon as the phone number is selected and prefilled in the TextField and retrive phone no from the text field?
Something like onCompletePrefill: () { sendOtp(); }

**Comment by jaumard** [comment]
Hello, you can provide a text controller, so you're free to listen to it and do what you need :)

**Comment by prodosdigital** [comment]
Hey, Thanks a lot for your help!
Somehow the controller.addListener didn't with PhoneFieldHint but worked perfectly with PhoneFormFieldHint.

**Comment by jaumard** [comment]
Strange as it should work too normally @grahamsmith we might have a bug in that place maybe since the refactoring

**Comment by grahamsmith** [comment]
Have you provided your own controller or are you trying to listen to the one created if one isn't provided?

We may have a bug but want to understand some better repo steps.

**Comment by prodosdigital** [comment]
> Have you provided your own controller or are you trying to listen to the one created if one isn't provided?
> 
> We may have a bug but want to understand some better repo steps.

I created my own controller added it as to the `controller` parameter of `PhoneFieldHint`
