### ISSUE TITLE
Not received SMS on emulator

### ISSUE THREAD

**Issue by tazik561** [jaumard/sms_autofill#116]
I have a question sir. 
I run example application and I press Listen for sms code and on emulator setting in phone section I  send SMS but nothing is added in application ? It is possible do that?

**Comment by jaumard** [comment]
Never tried on an emulator before, but I guess it should work if your emulator have play services installed, and that you have setup the hashcode on your SMS correctly

**Comment by tazik561** [comment]
How can I setup the hashcode on  SMS ? I just press `Get app signiture` and then I press Listen for sms code . Is it enough?

**Comment by tazik561** [comment]
How can I setup the hashcode on  SMS ? I just press `Get app signiture` and then I press Listen for sms code . Is it enough?

**Comment by tazik561** [comment]
I don't understand why need hashcode when sms centr wants to send sms? It is not possible to get otp sms without added hashcode to end of sms? instead of `<#> SampleApp: Your verification code is 1435
Z66b5+ou+DI` it just be `<#> Your verification code is 1435`

**Comment by jaumard** [comment]
@tazik561 I don't make the rules :) it's how the API is working, check this: https://developers.google.com/identity/sms-retriever/overview?hl=en
