### ISSUE TITLE
Build failed with an exception.

### ISSUE THREAD

**Issue by itsDepricated** [jaumard/sms_autofill#117]
### I'm getting this error while debugging

**copied your example code from pub.dev and pasted it to main.dart
and I tried to run ...**

this error occurred 
please help me to solve this 

`
Launching lib/main.dart on Redmi 6 Pro in debug mode...
lib/main.dart:1
../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sms_autofill-2.0.0/lib/sms_autofill.dart:195:24: Error: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
Try adding the name of the type of the variable or the keyword 'var'.
  final bool autoFocus;z
                       ^
../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sms_autofill-2.0.0/lib/sms_autofill.dart:195:24: Error: Expected ';' after this.
  final bool autoFocus;z
                       ^
../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sms_autofill-2.0.0/lib/sms_autofill.dart:202:9: Error: Constructor is marked 'const' so all fields must be final.
  const PhoneFieldHint({
        ^
../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/sms_autofill-2.0.0/lib/sms_autofill.dart:195:24: Context: Field isn't final, but constructor is 'const'.
  final bool autoFocus;z
                       ^
3

FAILURE: Build failed with an exception.
* Where:
Script '/home/dev-mallu/Development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/home/dev-mallu/Development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
![sms_auto_fill](https://user-images.githubusercontent.com/76783279/120600362-4fd50180-c466-11eb-8ce0-8c6dcd45ab4a.png)

`

**Comment by jaumard** [comment]
Should be ok now, but I think you edited the file by mistake there is a 'z' character that doesn't belong anywhere, updating to last version will probably fix this
