### ISSUE TITLE
It works on Android But doesn`t work in iOS 

### ISSUE THREAD

**Issue by wolrdboss** [jaumard/sms_autofill#120]
Hello This plugin works well on android but doesn`t work on ios.
I m testing with iPhone 8 ( iOS 14.6 ). Please help me how to solve it?

SmsAutoFill().getAppSignature doesn`t work.

**Comment by jaumard** [comment]
because there is no signature api on iOS side.

**Comment by wolrdboss** [comment]
Hello @jaumard 
Thanks for your reply. Please let me know how to solve the problem on the latest iOS.

**Comment by ccamba** [comment]
Same error here when migrating to sound null safety with version 2.0.0. 
With the previous version that came using 1.3.1 this does not happen

**Comment by ccamba** [comment]
@jaumard Correct, iOS does not return appSignature, it should not crash when invoked, like versions that are not null safety

**Comment by jaumard** [comment]
Fixed in 2.0.1 :)

**Comment by ccamba** [comment]
@jaumard Thanks man!
