### ISSUE TITLE
iOS: Unhandled Exception: type 'Null' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by ccamba** [jaumard/sms_autofill#124]
Hi, the version of package is 2.0.0, i'm running en i0S simulator, the error occurs in:

SmsAutoFill.getAppSignature
package:sms_autofill/sms_autofill.dart:43
<asynchronous suspension>

**Comment by jaumard** [comment]
Should be ok in 2.0.1 :) 
Thanks for the report!
