### ISSUE TITLE
Playstore signing messing up the hash

### ISSUE THREAD

**Issue by mohamoha6200** [jaumard/sms_autofill#127]
First of all , thank you to everyone who contributed to this very useful package !
The issue I was recently facing is related the generating the right hash for the live app on play store , it seems that play store auto signing has been enabled on our app which makes the live app signature different from the release apk generated using jks file locally.
The app used to have autofill working perfectly whether debug or release mode using the hash provided by the package itself on runtime but as soon as we wanted to publish it auto filling stopped working and it was clear that the hash we're sending (same one for release apks) is no longer useful and we need to update it according to live the play store signing.
The challenge here is that we tried every hint and workaround besides the google sms retrieval  docs to generate the hash from the .der file but without success (no auto fill = wrong hash in sms), being unable to get the hash directly from runtime since the app is live makes it very difficult to proceed and thus my post here , would appreciate any feedback , thank you.

**Comment by mohamoha6200** [comment]
Fixed ! the issue was I was using a wrong app package name in the commands google provided ! I was using the one in my android manifest rather than the one mentioned in build gradle applicationId.
Thank you.

**Comment by s4rath07** [comment]
Can you please provide details about how to get hash while releasing it on playstore?
