### ISSUE TITLE
version 2.1.0

### ISSUE THREAD

**Issue by briouyaasmae** [jaumard/sms_autofill#136]
After using version 2.1.0 I get this issue 
**E/AndroidRuntime(30428): java.lang.IllegalArgumentException: Receiver not registered: com.jaumard.smsautofill.SmsAutoFillPlugin$SmsBroadcastReceiver@ca372f0** 
and app crash

**Comment by jaumard** [comment]
Hey, thanks for the report, do you have steps to reproduce this please ?

**Comment by briouyaasmae** [comment]
<img width="428" alt="Screen Shot 2021-09-15 at 13 36 30" src="https://user-images.githubusercontent.com/51012596/133434874-b3f31d76-6b25-45b4-ac43-dd173ad51a97.png">
I'm using those functions and I'm calling them in initstate 

When I login for the first time and listen to otp, everything works well, but if I logout and login for the second time, the app crashes and this error is shown.

**Comment by jaumard** [comment]
Maybe that's because you listen to the code but actually never unregister it? 
Does it work better by adding:
```

  @override
  void dispose() {
    SmsAutoFill().unregisterListener();
    super.dispose();
  }

```

I'll make more test on my side see if I can reproduce it too

**Comment by briouyaasmae** [comment]
<img width="1935" alt="Screen Shot 2021-09-15 at 14 27 19" src="https://user-images.githubusercontent.com/51012596/133442069-c2d5402b-519a-44aa-b9d0-11ed9574ddca.png">
When I'm using SmsAutoFill().unregisterListener()

**Comment by jaumard** [comment]
ok very weird, so far I can't reproduce. Even don't see how the receiver can't be registered... 

Basically I create it like this:
```
unregisterReceiver();// unregister existing receiver
broadcastReceiver = new SmsBroadcastReceiver(new WeakReference<>(SmsAutoFillPlugin.this));
activity.registerReceiver(broadcastReceiver, new IntentFilter(SmsRetriever.SMS_RETRIEVED_ACTION));
```
So when it's created; it's registered. Then to unregister I do it only when it is not created. 
```
private void unregisterReceiver() {
        if (broadcastReceiver != null) {
            activity.unregisterReceiver(broadcastReceiver);
            broadcastReceiver = null;
        }
    }
```
It blow my mind :D 
I'll keep searching that! Thanks for the details

**Comment by jaumard** [comment]
So I have added a try/catch for now to avoid crash. As I can't reproduce of find what could go wrong... 
So should be good on 2.1.1. Let me know if there is any other issue.

**Comment by danghoanguet** [comment]
> So I have added a try/catch for now to avoid crash. As I can't reproduce of find what could go wrong... So should be good on 2.1.1. Let me know if there is any other issue.

So this issue is still there try catch just to prevent app crashes. I am facing an issue that after 5 minutes which is timeout i have to relisten by calling listenForCode again but sometimes  after relisten in onReceive status.getStatusCode() still 15(timeout)
