### ISSUE TITLE
Flutter app for iOS and Android

### ISSUE THREAD

**Issue by Acciaiodigitale** [jaumard/sms_autofill#16]
Hi @jaumard.

We send to our application a SMS as an OTP. 
With sms_autofill all goes well with Android. 
But  on iOS the autofill doesn't work.
I added Push Notification capabilities to the app.
What I miss?
Thank for the help!

**Comment by jaumard** [comment]
Hello :) 

This package only do Android :) last time I checked (that's a lot of time ^^) flutter was doing the job of showing the code on the keyboard and user has just to click on it.

If it's not the case anymore I don't think there is anything you can do except open an issue on flutter repo. 

I'm closing this as there is nothing I can do :/
