### ISSUE TITLE
is it possible  not using await SmsAutoFill().listenForCode; and code will work

### ISSUE THREAD

**Issue by Manishmg3994** [jaumard/sms_autofill#163]
i am using getx and found it hard to implement
 ```
await SmsAutoFill().listenForCode;
```
but i wish someone to tell me that this is  necessary or not
means code will work or not

**Comment by Hiteshc29** [comment]
> i am using getx and found it hard to implement
> 
> ```
> await SmsAutoFill().listenForCode;
> ```
> 
> but i wish someone to tell me that this is necessary or not means code will work or not

Yes it is necessary, it will listen to the code that you will receive in the SMS
