### ISSUE TITLE
Change of Copyright notice

### ISSUE THREAD

**Issue by lubovtorina** [jaumard/sms_autofill#175]
Hello!
Could you change Copyright notice in your MIT License (software sms_autofill) and add the author's name and surname, bacause the author's nickname "jaumard" can be changed in the future and this can make it difficult to identify the copyright owner of your software.
Thank you in advance!

**Comment by lubovtorina** [comment]
@jaumard, ping...

**Comment by jaumard** [comment]
It is changed, but don't really matter with MIT license as you can do whatever you want with the code without mentioning me.
