### ISSUE TITLE
sms autofill is not capturing OTP on android 12 devices.

### ISSUE THREAD

**Issue by Sayedmdkaif** [jaumard/sms_autofill#176]
sms autofill is not capturing OTP on android 12 devices..

Not giving any error.

**Comment by dkdanish98** [comment]
Hi @Sayedmdkaif 
Did you get any solution?

**Comment by Danc-0** [comment]
Hello @Sayedmdkaif and @dkdanish98 I am facing this challenge on Android 12 or higher, by any chance did you find a workaround on the same?

**Comment by Sayedmdkaif** [comment]
No, sorry.

**Comment by jaumard** [comment]
should be ok on 2.4.0
