### ISSUE TITLE
E/MethodChannel#sms_autofill(17327): Failed to handle method call

### ISSUE THREAD

**Issue by amit-onappr** [jaumard/sms_autofill#18]
E/MethodChannel#sms_autofill(17327): Failed to handle method call
E/MethodChannel#sms_autofill(17327): java.lang.IllegalArgumentException: Receiver not registered: com.jaumard.smsautofill.SmsAutoFillPlugin$SmsBroadcastReceiver@2709f01
E/MethodChannel#sms_autofill(17327): 	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1297)
E/MethodChannel#sms_autofill(17327): 	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1522)
E/MethodChannel#sms_autofill(17327): 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:659)
E/MethodChannel#sms_autofill(17327): 	at com.jaumard.smsautofill.SmsAutoFillPlugin.onMethodCall(SmsAutoFillPlugin.java:119)
E/MethodChannel#sms_autofill(17327): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#sms_autofill(17327): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#sms_autofill(17327): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#sms_autofill(17327): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#sms_autofill(17327): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#sms_autofill(17327): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#sms_autofill(17327): 	at android.app.ActivityThread.main(ActivityThread.java:6863)
E/MethodChannel#sms_autofill(17327): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#sms_autofill(17327): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/MethodChannel#sms_autofill(17327): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter (17327): ResendOTPButtonWidget :: disposed

**Comment by amit-onappr** [comment]
My bad. I did called unregister post the OTP message was read.

**Comment by Topiya** [comment]
@amit-onappr Can you please provide sample of your working code because when I tried,  OTP code from SMS is not getting autofilled in PinFieldAutoFill and can you please let me know do I need to fetch/read code from SMS and set the value to currentCode param of PinFieldAutoFill or it will be filled automatically ?

**Comment by izabekz** [comment]
@amit-onappr can you explain pls why calling unregister post the OTP message was read is bad, I have the same problem now, if it is bad, when should I unregister the receiver?
