### ISSUE TITLE
Error pin_input_text_field - No named parameter 'toolbarOptions'

### ISSUE THREAD

**Issue by astraube** [jaumard/sms_autofill#181]
Because of the plugin update "pin_input_text_field", the sms_autofill is breaking my project.

Error: sms_autofill.dart:104:7: Error: No named parameter with the name 'toolbarOptions'.
      toolbarOptions: ToolbarOptions(paste: true),

Commit pin_input_text_field: https://github.com/TinoGuo/pin_input_text_field/pull/81/files#diff-a6c233609d7bb00957deda2f9068860ebdf60e0fecd9a2d48b0553daa664a863

**Comment by mzdm** [comment]
yes, same

temporary solution, in your project is to add the old version to `dependency_overrides`:

```yaml
dependency_overrides:
  pin_input_text_field: "4.2.0"

```

**Comment by achernoprudov** [comment]
Fixed in #180

**Comment by jaumard** [comment]
should be ok on 2.4.0
