### ISSUE TITLE
Error: Cannot invoke a non-'const' constructor where a const expression is expected.

### ISSUE THREAD

**Issue by ManmohanTalwar** [jaumard/sms_autofill#186]
I'M facing this issue on latest Flutter stable sdk i.e. SDK 3.7.3.

../../../.pub-cache/hosted/pub.dev/sms_autofill-2.2.0/lib/sms_autofill.dart:73:31: Error: Cannot invoke a non-'const' constructor where a const expression is expected.
Try using a constructor or factory that is 'const'.
      this.decoration = const UnderlineDecoration(
                              ^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

Can you provide a solution for this. I tried creating a PR for the fix, but it is denying me to create one.

**Comment by sohamThence** [comment]
While the they make the change consider using 
https://github.com/sohamThence/sms_autofill

**Comment by manishkummar21** [comment]
what is the solution for above issue

**Comment by manishkummar21** [comment]
Its creating more problem for releasing

**Comment by sohamThence** [comment]
> Its creating more problem for releasing

@manishkummar21 are you using the fix?

**Comment by manishkummar21** [comment]
Yes

**Comment by manishkummar21** [comment]
Please merge this changes and release new version

**Comment by bsglm** [comment]
sms_autofill: 2.2.0 upgrade to sms_autofill: 2.3.0 problem is solved

**Comment by 10kesh** [comment]
you can use this package : https://pub.dev/packages/otp_pin_field

**Comment by shivam0139** [comment]
you can use this package : https://pub.dev/packages/otp_pin_field

**Comment by SaraW011** [comment]
> what is the solution for above issue

take out the initial MaterialApp 'const' worked for me.
