### ISSUE TITLE
Hash string from getAppSignature not working for release apk

### ISSUE THREAD

**Issue by shanazainab** [jaumard/sms_autofill#19]
Sms autofill is only working while using debug apk. Not reading sms otp while using release version with google app signing

**Comment by BeDaut** [comment]
because debug and release versions have different hash, check this link, it helped me to get my prod hash https://developers.google.com/identity/sms-retriever/verify#computing_your_apps_hash_string

**Comment by jaumard** [comment]
Yes debug and prod probably have different hash so you need to update your SMS content with the right one.
