### ISSUE TITLE
App crash on Android 14 OS

### ISSUE THREAD

**Issue by jigarempyreal** [jaumard/sms_autofill#208]
listenForCode() method throws the error.

One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

**Comment by Akramjon-koder** [comment]
when i upgrade version to 34 from gradle i get error.

**Comment by maksym-ostrovyj-ew** [comment]
got the same

**Comment by PawanFyers** [comment]
Same error, any solution ? @jaumard

**Comment by spaquis** [comment]
Hey,
If it's already fixed, can you release a 2.3.1 ? 
thanks

**Comment by yogeshelevn** [comment]
Hey, @jaumard I checked with main branch code. for Android 14, sms_autofill working fine. I urge you to release 2.3.1 version for production. this will help us a lot. Thanks.

**Comment by jaumard** [comment]
should be ok on 2.4.0
