### ISSUE TITLE
la nueva versión de gradle 8.4.0 es incompatible con sms_autofill 

### ISSUE THREAD

**Issue by LuisGutierrezArone** [jaumard/sms_autofill#209]
Hola a toda la comunidad, he visto reciente que el paquete tiene problemas con la nueva versión de gradle de android
la solución que hice es:
En el archivo build.gradle

agregar lo siguiente
android {
    if (project.android.hasProperty("namespace")) {
        namespace 'com.jaumard.smsautofill'
    }

compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

la condicional es para que la verificación de la existencia de namespace que en las últimas versiones de gradle y android lo están trabajando, espero que actualicen el paquete, yo lo corregí en mi local aunque no es la manera correcta pero con ello solucioné el inconveniente de versión.

**Comment by jaumard** [comment]
should be ok on master, will do a release later
