### ISSUE TITLE
BackSpace/Delete is not working.

### ISSUE THREAD

**Issue by harsh-trentiums** [jaumard/sms_autofill#21]
How to remove entered OTP from the using backspace. Is there any way to reset or clear the filled pins?

**Comment by renenucci** [comment]
Can u show ur code?
Is the pinfield inside a StreamBuilder and are u using bloc pattern?

**Comment by harsh-trentiums** [comment]
Hi, @renenucci I'm using provider pattern. The issue is I can enter the pin but i can't remove it. I'm posting code snippets to give you a more understanding of the issue.

`_getVerifyCard(BuildContext context) {
    listenToSMSCode();

    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Container(
        width: MediaQuery.of(context).size.width,
        child: Card(
          color: white,
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: Column(
              children: <Widget>[
                Text(
                  verify_title,
                  textAlign: TextAlign.center,
                  style: TextStyle(
                      color: black, fontSize: 18, fontWeight: FontWeight.w600),
                ),
                SizedBox(
                  height: 10,
                ),
                Image.asset(
                  icVerify,
                ),
                SizedBox(
                  height: 10,
                ),
                Text(
                  otp_msg,
                  textAlign: TextAlign.center,
                  style: TextStyle(
                      color: black, fontSize: 18, fontWeight: FontWeight.w300),
                ),
                SizedBox(
                  height: 10,
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: <Widget>[
                    Text(
                      "${selectedCode.dialingCode} ${_mobileNumberController.text.trim()}",
                      textAlign: TextAlign.center,
                      style: TextStyle(
                          color: black,
                          fontSize: 18,
                          fontWeight: FontWeight.w600),
                    ),
                    InkWell(
                      onTap: () {
                        _loginProvider.updateScreenType(ScreenType.LoginScreen);
                      },
                      child: Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: Icon(
                          Icons.edit,
                        ),
                      ),
                    )
                  ],
                ),
                SizedBox(
                  height: 10,
                ),
                Text(
                  enter_digits,
                  textAlign: TextAlign.center,
                  style: TextStyle(
                      color: black, fontSize: 18, fontWeight: FontWeight.w300),
                ),
                Center(
                  child: Container(
                    width: 120,
                    child: PinFieldAutoFill(
                      onCodeChanged: (value) {
                        print("OnCodeChanged ->>>>>> $value");
                        detectedOTP = value;
                        if (detectedOTP.trim().length >= 6) {
                          _verifyOTP();
                        }
                      },
                      onCodeSubmitted: (value) {
                        if (detectedOTP.trim().length >= 6) {
                          _verifyOTP();
                        }
                      },
                      decoration: UnderlineDecoration(
                          textStyle: TextStyle(color: Colors.black),
                          color: Colors.grey),
                      codeLength: 6,
                      autofocus: true,
                      keyboardType: TextInputType.number,
                    ),
                  ),
                ),
                SizedBox(
                  height: 20,
                ),
                _loginProvider.loginButtonState == ViewState.Busy
                    ? CircularProgressIndicator()
                    : MaterialButton(
                        onPressed: () {
                          _verifyOTP();
                        },
                        minWidth: MediaQuery.of(context).size.width,
                        color: redButtonColor,
                        child: Padding(
                          padding: const EdgeInsets.all(13.0),
                          child: Text(
                            verify_login,
                            style: TextStyle(
                                color: white,
                                fontSize: 18,
                                fontWeight: FontWeight.w400),
                          ),
                        ),
                      ),
                SizedBox(
                  height: 10,
                ),
                ResendTimerWidget(_validatePhoneNumber),
                SizedBox(
                  height: 10,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }`

**Comment by harsh-trentiums** [comment]
Ok so i found a crack of it. So I was calling webservice when detected code length reaches to the 6 characters and that's somehow dismissing the focus of current pin code fields. So I just simply dismissed the keyboard before calling API which resolved my issue. Because second time user will manually click on the pin fields which will make them focussed again.

**Comment by Topiya** [comment]
@harsh-trentiums Can you please let me know how did you set verification code from SMS into currentCode param of PinFieldAutoFill/TextFieldPinAutoFill ? Because when I tried, OTP code from SMS is not getting autofilled in PinFieldAutoFill and can you please let me know do I need to fetch/read code from SMS and set the value to currentCode param of PinFieldAutoFill or it will be filled automatically ?

**Comment by harsh-trentiums** [comment]
Hi,

There is one method in the library which is named as “getAppSignature”. You’ve to identify your app’s signature and that signature must be attached to your SMS.Final output of your sms would be

<#> ExampleApp: Your code is 123456
"FA+9qCX9VSu” <— Replace your app’s signature by calling above method.

And then try to listen to sms verification code by using this method

await SmsAutoFill().listenForCode;

Let me know in case if you need any other help.
