### ISSUE TITLE
Will using this plugin reject our app from the Google Play Store

### ISSUE THREAD

**Issue by praneethdamian** [jaumard/sms_autofill#216]
Hello there.
Kindly let me know is it ok to use this plugin in an application I plan to submit to the Google Play Store. The application my team plans to develop is a financial application. Since we are listening  to sensitive data. My team has a concern regarding the Google Play policies that might conflict by the use of this flutter plugin.

Thank you.

**Comment by jaumard** [comment]
No as I use public API, depending on what you do with the data you should declare it on google console privacy data.
