### ISSUE TITLE
Update your last version in pub dev

### ISSUE THREAD

**Issue by lucLacerda** [jaumard/sms_autofill#221]
In your last commit, you made a fix for android 14 updates (API 34), but you did not release it to the pub dev

![image](https://github.com/jaumard/sms_autofill/assets/89214092/f95fadb6-5b35-417a-a6f3-46bca2595f13)

![image](https://github.com/jaumard/sms_autofill/assets/89214092/e8fb964c-ad87-4cd3-9c98-3dab4e434843)

**Comment by JgomesAT** [comment]
It would be great to publish this version

**Comment by jaumard** [comment]
2.4.0 on pub, sorry for this
