### ISSUE TITLE
PhoneFieldHint not working on Android 14

### ISSUE THREAD

**Issue by seeamarnath** [jaumard/sms_autofill#225]
PhoneFieldHint widget is not showing the available phone numbers. the dialog just closing as soon as the user clicks on the PhoneFieldHint widget.  Looks happening on Android 14.

**Comment by AryanBisht-03** [comment]
Did u find any solution buddy..?

**Comment by seeamarnath** [comment]
nope.

**Comment by Shub0327** [comment]
did anyone found solution for this?

**Comment by sahilmehra98** [comment]
Check PR #232

**Comment by jaumard** [comment]
thanks to @sahilmehra98 should be ok on 2.4.0

**Comment by AryanBisht-03** [comment]
@jaumard when can I expect it 2.4.0..?

**Comment by jaumard** [comment]
It's live already
