### ISSUE TITLE
How to fill selected phone number in my textfield using requestPhoneHint.

### ISSUE THREAD

**Issue by rinkuanuragkumar** [jaumard/sms_autofill#23]
Explain how to fill selected phone number in my textfield using requestPhoneHint hint method.

void initState(){
    focusNode.addListener(() async {
      if (focusNode.hasFocus && !_hintShown) {
        _hintShown = true;
        final completePhoneNumber = await _autoFill.hint;
        print("Autofill");
        print(completePhoneNumber);
      }
    });
    super.initState();

  }

TextField(
                autofocus: false,
                focusNode: focusNode,
                decoration: InputDecoration(
                  suffixIcon: Platform.isAndroid
                    ? IconButton(
                      icon: Icon(Icons.phonelink_setup),
                      onPressed: () async {
                        final completePhoneNumber = await _autoFill.hint;
                        //print("Autofill2");
                        //print(completePhoneNumber);
                      },
                    )
                    : null,
                ),
                controller: controller,
                keyboardType: TextInputType.phone,
                onChanged: (val){
                  print(val);
                },
              ),

**Comment by Renatinaveen** [comment]
For me it's not returning the phone number when i select.I have this plugin using in 2 projects in one project it's works fine but in another project phone number doesn't return when it's selected.

**Comment by grahamsmith** [comment]
Going to close this issue due to low activity. Happy to revisit in the future if still an issue.
