### ISSUE TITLE
Crash Error: App crashes when sms is received for android 14 devices

### ISSUE THREAD

**Issue by ROD-MASAMI** [jaumard/sms_autofill#236]
One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
E/AndroidRuntime(23636): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3183)
E/AndroidRuntime(23636): 	at android.os.Parcel.createException(Parcel.java:3167)
E/AndroidRuntime(23636): 	at android.os.Parcel.readException(Parcel.java:3150)
E/AndroidRuntime(23636): 	at android.os.Parcel.readException(Parcel.java:3092)
E/AndroidRuntime(23636): 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5860)
E/AndroidRuntime(23636): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1853)
E/AndroidRuntime(23636): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1793)
E/AndroidRuntime(23636): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1781)
E/AndroidRuntime(23636): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:757)
E/AndroidRuntime(23636): 	at com.jaumard.smsautofill.SmsAutoFillPlugin$2.onSuccess(SmsAutoFillPlugin.java:114)
E/AndroidRuntime(23636): 	at com.jaumard.smsautofill.SmsAutoFillPlugin$2.onSuccess(SmsAutoFillPlugin.java:108)
E/AndroidRuntime(23636): 	at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
E/AndroidRuntime(23636): 	at android.os.Handler.handleCallback(Handler.java:959)
E/AndroidRuntime(23636): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(23636): 	at android.os.Looper.loopOnce(Looper.java:232)
E/AndroidRuntime(23636): 	at android.os.Looper.loop(Looper.java:317)
E/AndroidRuntime(23636): 	at android.app.ActivityThread.main(ActivityThread.java:8592)
E/AndroidRuntime(23636): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23636): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
E/AndroidRuntime(23636): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
E/AndroidRuntime(23636): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(23636): 	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14467)
E/AndroidRuntime(23636): 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2648)
E/AndroidRuntime(23636): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2822)
E/AndroidRuntime(23636): 	at android.os.Binder.execTransactInternal(Binder.java:1500)
E/AndroidRuntime(23636): 	at android.os.Binder.execTransact(Binder.java:1444)

**Comment by shivansh22agra** [comment]
Same

**Comment by ROD-MASAMI** [comment]
> Same
Update to latest version and make sure compile sdk is 34 and minimum sdk is 24

**Comment by ROD-MASAMI** [comment]
Update to latest version and make sure compile sdk is 34 and minimum sdk is 24

**Comment by shivansh22agra** [comment]
thanks worked

**Comment by anantnimbalkar** [comment]
still not working after updating also any solution?
