### ISSUE TITLE
AndroidX versions broken

### ISSUE THREAD

**Issue by kbrmimbyl** [jaumard/sms_autofill#27]
This is a great plugin and 0.0.1 (before move to AndroidX) works perfectly. I've tried all the versions post the AndroidX migration (1.0.0. 1.0.1, 1.1.1), and none of them work. The Phone Hint feature crashes the app and the SMS retrieval doesn't happen. I'm willing to help fix this. Any pointers, @jaumard?

**Comment by jaumard** [comment]
Are you able to reproduce on the example app of this project ? might be easier if I see the crash

**Comment by kbrmimbyl** [comment]
No, I haven't tried the example app but others have... https://github.com/jaumard/sms_autofill/issues/22

**Comment by kbrmimbyl** [comment]
Apologies, @jaumard. Only the phone hint feature is broken in the AndroidX versions. SMS retrieval wasn't working for me because I was using the debug signature to sign the release version. I'm going ahead and closing this issue since we can continue on https://github.com/jaumard/sms_autofill/issues/22.
