### ISSUE TITLE
If you set custom TextField the function hint dissappear

### ISSUE THREAD

**Issue by alexviquez** [jaumard/sms_autofill#3]
Hi @jaumard this is a very good plugin ! i found an issue,
If you using PhoneFieldHint and assign child TextField customized, the functionality of Hint dissappear, check this code 

`builder: (_, snapshot) => PhoneFieldHint(
            autofocus: true,
            child: TextField(
              decoration: InputDecoration(
                hintText: 'Tu Número',
                errorText: snapshot.error,
                errorStyle: SignUpConfiguration.getErrorFormStyle(context),
              ),
              onChanged: bloc.onPhoneNumberChanged,
              keyboardType: TextInputType.phone,
              autocorrect: false,
              style: TextStyle(
                fontFamily: 'Roboto',
                fontSize: Utils.getFontSize(context, 20.0),
              ),
            ),
          )`

**Comment by jaumard** [comment]
Hi @alexviquez sorry for very late reply, I don't have much time for looking into that but I'll gladly review and merge a PR addressing this ! 

Thanks !

**Comment by vasurana** [comment]
Hey, were you able to resolve this? I am setting my own custom TextField and but I am facing this same issue and hints are not popping up. Please help.

**Comment by jack24254029** [comment]
Hi @vanyasem 
Can you paste your code here?
I use code of the @alexviquez , I don't find problem.

Code: 
```dart
PhoneFieldHint(
  autofocus: true,
  child: TextField(
    decoration: InputDecoration(
      hintText: 'Hint Text',
      errorText: 'Error Text',
      errorStyle: TextStyle(
        fontFamily: 'Roboto',
        fontSize: 20.0,
      ),
    ),
    onChanged: (String s) {
    },
    keyboardType: TextInputType.phone,
    autocorrect: false,
    style: TextStyle(
      fontFamily: 'Roboto',
      fontSize: 20.0,
    ),
  ),
),
```
Image: 
![image](https://user-images.githubusercontent.com/13265628/97100627-529d9600-16d0-11eb-9991-8858c56ada2b.png)

**Comment by jack24254029** [comment]
Do you mean this?

![image](https://img-blog.csdnimg.cn/20190306162128566.gif)
the gif from https://blog.csdn.net/yuzhiqiang_1993/article/details/88204031

**Comment by jaumard** [comment]
I guess the solution is simple here, if you put your own textField you also need to provide the focusNode, if you don't the hint will never appear as the widget can't know when to show it.

**Comment by vasurana** [comment]
Hi @jaumard It won't work even if I tap on the TextField. Can you please guide us on how to set focusNode in this particular case. I tried setting one but it is still not working.
