### ISSUE TITLE
Sms User Consent Api

### ISSUE THREAD

**Issue by Viper-Bit** [jaumard/sms_autofill#34]
Hi @jaumard,
Can u implement sms user consent api in this plugin too ? Is there any chance ?
This is very good for some country that cant send hash code in sms
[https://developers.google.com/identity/sms-retriever/user-consent/request](https://developers.google.com/identity/sms-retriever/user-consent/request) 
[https://medium.com/androiddevelopers/automatic-sms-verification-with-sms-user-consent-da8c16135e25](https://medium.com/androiddevelopers/automatic-sms-verification-with-sms-user-consent-da8c16135e25)

**Comment by jaumard** [comment]
Hello :)

Look like a good idea and addition to the plugin, but I'll not have time to implement it any time soon. If someone is willing to create a PR with that I'll gladly review and merge it !

**Comment by grahamsmith** [comment]
Going to close this due to inactivity. Happy to reopen it in the future.
