### ISSUE TITLE
CodeAutoFill mixin issue while listening for code

### ISSUE THREAD

**Issue by pedromassango** [jaumard/sms_autofill#35]
There is a issue in the `CodeAutoFill` mixin. The docs says:

> `listenForCode()` to listen for the SMS code from the native plugin when SMS is received, need to be called on your `initState`.

but after some tests it seems that this is not enough. If you just do this code will not get detected. In order to start listening for the OTP you need to call both in the `initState`:

```
  @override
  void initState() {
    super.initState();
   
    listenForCode();
    SmsAutoFill().listenForCode;
  }
```

If you do not call `SmsAutoFill().listenForCode;` after `listenForCode()` you will never receive the OTP code in the Flutter app.

**Comment by rfitz123** [comment]
I'm also trying to use the mixin and haven't gotten it to catch the code yet. I use `with CodeAutoFill`, call `listenForCode()` and `SmsAutoFill().listenForCode` in `initState` like above, I implement `codeUpdated()`. `codeUpdated()` called twice in a row about one minute after receiving the text, but `code` was null. Did you have any other difficulties that might account for this? Really hard to debug this :/

**Comment by pedromassango** [comment]
Yes. You may receive code updates many times and most of the time it will be null.

What I did was to create a Boolean and once I receive a valid code it se it value to true and ignore the precedent of the codeUpdated

**Comment by pedromassango** [comment]
@jaumard Are you still accepting PR on this repository?

**Comment by jaumard** [comment]
Sure @pedromassango !

**Comment by pedromassango** [comment]
@jaumard  please review the PR that solves this issue!

**Comment by pedromassango** [comment]
@rfitz123 make sure to update your dependency to have this issue fixed on your sproject.

**Comment by maheshperi** [comment]
Not receiving sms code. I have implemented all methods.

@override
  void initState() {
    // TODO: implement initState
    super.initState();

    print("initstate method");

   // Implementing sms auto fill here...
    listenForCode();
    SmsAutoFill().listenForCode;

    SmsAutoFill().getAppSignature.then((signature) {
      setState(() {
        appSignature = signature;
      });
    });
  }

I am calling backend api service by sending mobile number. getting sms to my mobile message inbox. 

Will it automatically get sms code from inbox message ?

i dont know what is the wrong i am doing. Please help me.

Thanks.
Mahesh.

**Comment by pedromassango** [comment]
Have you added app signature in your sms?

**Comment by maheshperi** [comment]
No. Can you please tell me how to do that ? 
I am not aware of native android development.

**Comment by pedromassango** [comment]
Add the string returned bellow at the end of the message received: 
```
SmsAutoFill().getAppSignature.then((signature) {
  setState(() {
    appSignature = signature;
  });
});
```

Read more here: https://developers.google.com/identity/sms-retriever/verify#1_construct_a_verification_message

**Comment by maheshperi** [comment]
Thank you. I will check it.

**Comment by agubha** [comment]
> @pedromassango I'm also trying to use the mixin and haven't gotten it to catch the code yet. I use `with CodeAutoFill`, call `listenForCode()` and `SmsAutoFill().listenForCode` in `initState` like above, I implement `codeUpdated()`. `codeUpdated()` called twice in a row about one minute after receiving the text, but `code` was null. Did you have any other difficulties that might account for this? Really hard to debug this :/

Did you solved your issue!
I am having same issue
received 2 null value on codeUpdated() 
and nothing after that
It is only receiving null so adding boolean to check if it not null will result in never reaching not null condition!

**Comment by pedromassango** [comment]
> I am having same issue

Have you added the signature code at the end of your messages?

**Comment by swatiElegant** [comment]
Hi @pedromassango I will blessed if you would help in in this issue...I tried many time with different ways..but didn't get SMS event

**Comment by pedromassango** [comment]
> Hi @pedromassango I will blessed if you would help me in this issue...I tried many time with different ways..but didn't get SMS event

What have you tried? Flutter now supports autofill out of the box
