### ISSUE TITLE
Dispose Issue

### ISSUE THREAD

**Issue by gouthamkumar253** [jaumard/sms_autofill#37]
Hi, Thanks for this package and everything works great. But when dispose is called, I get this error in the console.

E/flutter (29786): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Receiver not registered: com.jaumard.smsautofill.SmsAutoFillPlugin$SmsBroadcastReceiver@9cc9569, null)

Any idea what it is and how to solve it?

**Comment by adolfdsilva** [comment]
+1

**Comment by jaumard** [comment]
Fixed on last version
