### ISSUE TITLE
While typing manually, text field resets

### ISSUE THREAD

**Issue by dheeraj2dj** [jaumard/sms_autofill#38]
version: 1.2.0

While I am typing the OTP (manually), after started listening to code, the text field resets before I finish typing thr OTP.

The behaviour I am trying to implement: If SMS received, autofill & submit. If not received in the this phone, type it manually. Now when typing manually, the code resets in the textfield.

How can I set this functionality? May be while typing, not reseting the text field to empty.

**Comment by is10vmust** [comment]
same Here

**Comment by farazu101** [comment]
```
onCodeChanged: (value) {
     _code = value;
},
```

i.e total code will look like.

```
PinFieldAutoFill(
     decoration: UnderlineDecoration(
     textStyle: TextStyle(fontSize: 20, color: Colors.black)),
     currentCode: _code,
     onCodeChanged: (value) {
        _code = value;
     },
),
```

**Comment by mahmudemam** [comment]
The reason for that is that the widget is rebuilt every time the keyboard is opened or closed.

The solution is to extract the `PinFieldAutoFill` in an external widget has a constant constructor, and create an instance from this widget as constant which will avoid the rebuilding to rebuild it.

I know that this solution my be difficult depending on your code structure, but it works for me.

**Comment by jaumard** [comment]
Should be better on the last version :)
