### ISSUE TITLE
getAppSignature returning null

### ISSUE THREAD

**Issue by rfitz123** [jaumard/sms_autofill#41]
So `await SmsAutoFill().getAppSignature` was working until I changed the package name / bundle id, and is now returning null. I tried to look into the code for the plugin, but was having a hard time finding the issue. The only notable change with the package name that I can think of is the fact that the package name / bundle id is com.something rather than com.something.somethingelse. Is this still an acceptable format for this feature?

**Comment by jaumard** [comment]
There is no specific format for the package, it's retrieved automatically so any should work. Are you testing that on Android ? Because on iOS it always return null :) 
Saying that because it append to me I was testing in iOS and it was making me crazy lol

**Comment by jaumard** [comment]
Closing as no update
