### ISSUE TITLE
Sms Not automatically reading in live version

### ISSUE THREAD

**Issue by arshadm25** [jaumard/sms_autofill#43]
I have used this package in order to verify my user on login. and when i added it to the play store without recieve sms permission the app doesn't automatically filling the pin fields

**Comment by Renatinaveen** [comment]
Normally The hash string changes after you the app to playstore so try getting the hash key from the playstore version

**Comment by Suhrt** [comment]
I have the same issue. I followed https://developers.google.com/identity/sms-retriever/verify#computing_your_apps_hash_string to get the play store hash key.

**Comment by arshadm25** [comment]
> Normally The hash string changes after you the app to playstore so try getting the hash key from the playstore version

I was sending the hash string with the request each time

**Comment by jaumard** [comment]
Working in production for me too, I suppose you should check that the hash is correct for your release build

**Comment by yash365** [comment]
Hello @jaumard @Suhrt i followed all the using keytool mentioned here : https://developers.google.com/identity/sms-retriever/verify#computing_your_apps_hash_string. 

i got the 11 digit has string but it is not working and getting this output after following command:

Command:
`keytool -exportcert -alias PlayDeploymentCert -keystore MyProductionKeys.keystore | xxd -p | tr -d "[:space:]" | echo -n com.example.myapp `cat` | sha256sum | tr -d "[:space:]-" | xxd -r -p | base64 | cut -c1-11`

Output:
```
Warning:
The JKS keystore uses a proprietary format. It is recommended to migrate to PKCS12 which is an industry standard format 
tr: write error
```

Don't know why "**tr: write error**" is coming ?
