### ISSUE TITLE
Cannot change OTP(or pin) after the OTP is submitted.

### ISSUE THREAD

**Issue by manishag777** [jaumard/sms_autofill#47]
When otp validation is failed from the server, I want user to edit it. But unfortunately it's not working. Please correct me if I would have been doing any programatical mistake.

**Comment by jaumard** [comment]
Normally you can edit it, it's just a textField so user can edit it at anytime

**Comment by AshlinQoruz** [comment]
I am facing the same isssue. Once i enter the otp and submit. if the otp validation is failed from the server i need need users to edit. when i enter the otp fields keypad is appearing but cursor is not visible and on onCodeChanged is not working as well
