### ISSUE TITLE
11-character hash string  keep changing 

### ISSUE THREAD

**Issue by ShubhamKarki** [jaumard/sms_autofill#49]
My keyStore jks file is same but 11-character hash string  is keep changing after few days.

**Comment by jaumard** [comment]
If it changes it mean you didn't sign with the same keystore... Check you keystore is same in debug AND release or it indeed changes
Anyway I can't do anything about that.

**Comment by ShubhamKarki** [comment]
It,s my bad my package name has changed  therefore string value has changed
