### ISSUE TITLE
Build error when add sms auto fill 

### ISSUE THREAD

**Issue by DanialV** [jaumard/sms_autofill#5]
Here is the error log I think the error is clear and doesn't need any further explanation 
```
/home/danial/Android/flutter/.pub-cache/hosted/pub.dartlang.org/sms_autofill-1.0.0/android/src/main/java/com/jaumard/smsautofill/SmsAutoFillPlugin.java:13: error: cannot find symbol
import androidx.annotation.NonNull;
                          ^
  symbol:   class NonNull
  location: package androidx.annotation
/home/danial/Android/flutter/.pub-cache/hosted/pub.dartlang.org/sms_autofill-1.0.0/android/src/main/java/com/jaumard/smsautofill/SmsAutoFillPlugin.java:105: error: cannot find symbol
                    public void onFailure(@NonNull Exception e) {
                                           ^
  symbol: class NonNull
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sms_autofill:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
Finished with error: Gradle task assembleDebug failed with exit code 1
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
```

**Comment by pavankumarkatakam** [comment]
Same issue getting for me too.

**Comment by pavankumarkatakam** [comment]
Flutter run is working fine but unable to build the APK.

**Comment by bigworld12** [comment]
same error, any updates on this ?

**Comment by iamatul9074** [comment]
delete flutter/.pub-cache and run again that will help you

**Comment by earyzhe** [comment]
same error here
 
Running with this setup: 
[✓] Flutter (Channel master, v1.10.10-pre.8, on Mac OS X 10.14.6 18G95, locale en-GB)
    • Flutter version 1.10.10-pre.8 at /Users/earyzhe/SDKs/flutter
    • Framework revision 3a728a9b5b (27 hours ago), 2019-10-04 01:37:43 -0400
    • Engine revision a0605af402
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 b4688e9172)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/earyzhe/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 33.2.2
    • Dart plugin version 183.5901

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 9 (API 28) (emulator)
    • Andrew's iPhone           • 6aa0c9719a85c174869a09656237b42f23701a91 • ios         • iOS 13.1.1
    • macOS                     • macOS                                    • darwin-x64  • Mac OS X 10.14.6 18G95

**Comment by BeDaut** [comment]
#20 this will probably fix it for u

**Comment by jaumard** [comment]
Is it fixed now guys can I close it ?

**Comment by BeDaut** [comment]
@jaumard update the package on pub.dev please

**Comment by jaumard** [comment]
It's a working progress :) thanks! Closing this one
