### ISSUE TITLE
Cannot manually enter the text(pin) 

### ISSUE THREAD

**Issue by harishkunjithaya257** [jaumard/sms_autofill#50]
hey,

In the worst case if I won't receive SMS  i have enabled call option in which it should enable inputting the value.
here I am not able to edit or input the value even though setting the controller: TextController()

**Comment by jaumard** [comment]
Hello, would be easier to see some code ^^ or better an example to reproduce the problem

**Comment by Ranjithsp6** [comment]
Facing the same issue, @jaumard I tried the example widget PinFieldAutoFill. Autofill otp is working fine but couldn't enter manually.

**Comment by jack24254029** [comment]
Hi @Ranjithsp6 
I try `1.2.6` example widget `PinFieldAutoFill`, and it can enter code manually.

**Comment by grahamsmith** [comment]
Closing to to inactivity. If there is still an issue happy to take a look and reopen.

**Comment by sahooamit1405** [comment]
Is there any resolution to this problem.. still facing it in latest version.
