### ISSUE TITLE
[Querry] About AppSignature

### ISSUE THREAD

**Issue by parammittal162** [jaumard/sms_autofill#52]
Hi I hust have a querry that can i generate AppSignature for one Time and use it as a constant in my app Will it change for device to device or platform wise ? Will it remain constant after I built my App?

**Comment by parammittal162** [comment]
@jaumard can you help ?

**Comment by jaumard** [comment]
Signature works only on android, there is no equivalent for iOS. It stay constant until you sign your app with another keystore. So be careful if you have one different for debug and prod

**Comment by parammittal162** [comment]
ok Thanks @jaumard

**Comment by jaumard** [comment]
You're welcome
