### ISSUE TITLE
Add the capability to change the color of the text field after a value is entered into it.

### ISSUE THREAD

**Issue by nimi0112** [jaumard/sms_autofill#53]
Add the capability to change the color of the text field after a value is entered into it.

<img width="287" alt="Screenshot 2020-08-27 at 4 29 27 PM" src="https://user-images.githubusercontent.com/16234261/91434490-7c7a3e00-e882-11ea-8023-0125389e12ab.png">
 

Right now we cannot change the background color after the value is entered in it.

**Comment by jaumard** [comment]
If you want that you'll have to ask the package I use under the hook for the pin field, it's this one https://pub.dev/packages/pin_input_text_field until it support this capability I can't.

**Comment by nimi0112** [comment]
Hi, @jaumard  [TinoGuo](https://github.com/TinoGuo) has updated his library for this feature implementation, can you also please update your dependencies. https://github.com/TinoGuo/pin_input_text_field/pull/45/

**Comment by jaumard** [comment]
Just do pub update :) I don't need to update deps as I use range support
