### ISSUE TITLE
Showing Code error in Autosms

### ISSUE THREAD

**Issue by harishkunjithaya257** [jaumard/sms_autofill#56]
Hi,

please do cross-check the code, because I have been using SMS autofill for a while but this issue is new to me.
![rsz_1rsz_screenshot_from_2020-09-05_15-40-28](https://user-images.githubusercontent.com/68266782/92352991-f02b0f00-f0fc-11ea-8962-0f5b12644ad7.png)

**Comment by iommi87** [comment]
it comes from pin_input_text_field:3.1.0 dependency.

**Comment by jaumard** [comment]
Yes they have changed their API, from `color: Colors.black` to `colorBuilder: FixedColorBuilder(Colors.black)`
