### ISSUE TITLE
[feature request] please add support for AppSignature Helper

### ISSUE THREAD

**Issue by pavankumarkatakam** [jaumard/sms_autofill#6]
This plugin has generating the app signature dynamically using java, it will be nice if that feature also support in this plugin.

plugin : https://pub.dev/packages/sms_retriever

**Comment by jaumard** [comment]
Hello @pavankumarkatakam ! 

What's the point of having this in the plugin ? It's not needed to make it work. Do you what it only as an helper ?

**Comment by pavankumarkatakam** [comment]
Yes, only as an helper, My use case is there are different versions of my app builds with different certificates (for different companies) but connecting to same multitenant server, so while sending OTP app should identity itself with its app signature dynamically to server so that server will send the OTP with right app signature. Also there are difference in building at various stages like Prod, Dev, Test etc.

**Comment by jaumard** [comment]
Fixed with your PR :) thanks !
