### ISSUE TITLE
IoS support

### ISSUE THREAD

**Issue by Shakhboz95** [jaumard/sms_autofill#62]
Hello
Does this support IoS devices also?
If no how it works for Ios actually

Thanks beforehand

**Comment by jack24254029** [comment]
Hi @Shakhboz95 
This plugin only support Android.

You can see these documents from Apple.
https://support.apple.com/guide/iphone/automatically-fill-in-sms-passcodes-on-iphone-iphc89a3a3af/ios
https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_a_text_input_view?language=swift

I think `TextField` of Flutter does not support `UITextContentType ` of the iOS.

**Comment by akifarhan** [comment]
It is possible to add `autofillHints: const <String>[AutofillHints.oneTimeCode],` to the `PinFieldAutoFill()` widget so we can reuse the same widget for iOS and Android?

**Comment by jaumard** [comment]
It is not possible yes, but it need to be added to the library handling the textField, check the liked issue :)

**Comment by jaumard** [comment]
Done in 1.2.7
