### ISSUE TITLE
Not fetching the OTP from the message

### ISSUE THREAD

**Issue by Niroop4444** [jaumard/sms_autofill#67]
As per the document i do am initalizing await SmsAutoFill().listenForCode; just before you sending the phone number to the backend and also reading it by using await SmsAutoFill().listenForCode;, but never did the OTP gets autofilled in the PinFieldAutoFill

**Comment by Alecckie** [comment]
Same for me ... I even went ahead to copy the example code without editing it and it still does not read the OTP.

**Comment by jaumard** [comment]
Hello, be sure the hash code is correct in your SMS, it should correspond to the keystore used to sign the sign. If those are not align, you'll not fetch anything. If not I don't know what can be wrong... I have no issues on the device I tested, 
Have you tested on multiple ? can you specify which device and android version are not working pleas e?

**Comment by Niroop4444** [comment]
Yes you're right i just had missed the app signature part to give it to the backend, everything's working fine but the only issue is that it wont get automatically filled everytime apart from that everything's working perfectly good. A nice repo!!

**Comment by Alecckie** [comment]
Lemme just say that I too am ashamed for not noticing the signature. I had generated my own custom signature which ofcourse was not being recognized by the app. Maybe you might add in the Docs the importance of that signature
It works superbly now.
