### ISSUE TITLE
autovalideMode error

### ISSUE THREAD

**Issue by ashishoffice** [jaumard/sms_autofill#70]
/C:/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/pin_input_text_field-3.1.2/lib/src/widget/pin_widget.dart:369:13: Error: No named parameter with the name 'autovalidateMode'.
            autovalidateMode: autovalidateMode,
            ^^^^^^^^^^^^^^^^

**Comment by Kashif-Ali786** [comment]
Any solution for above error??

**Comment by ashishoffice** [comment]
no any solution

**Comment by Kashif-Ali786** [comment]
I face this error 2 hours ago, till now working on it to resolve

**Comment by ashishoffice** [comment]
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method requestPhoneHint on channel sms_autofill)

**Comment by ashishoffice** [comment]
please  can you fix the issue

**Comment by Kashif-Ali786** [comment]
I solve this error after running flutter upgrade

**Comment by ashishoffice** [comment]
I have used flutter version number 1.20.2 .. these are not working

**Comment by Kashif-Ali786** [comment]
My updated version is 1.22.5

**Comment by thealiflab** [comment]
> I solve this error after running flutter upgrade

Solved my problem as well.

**Comment by jaumard** [comment]
seems solved :)
