### ISSUE TITLE
No implementation found for method requestPhoneHint on channel sms_autofill

### ISSUE THREAD

**Issue by ashishoffice** [jaumard/sms_autofill#71]
Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method requestPhoneHint on channel sms_autofill))

**Comment by grahamsmith** [comment]
@ashishoffice is this still the case on the latest release?

**Comment by jaumard** [comment]
Closing as no answer, don't hesitate to reopen if needed.

**Comment by kateile** [comment]
@jaumard I am getting the same error on latest release 

> E/flutter ( 5966): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method unregisterListener on channel sms_autofill)
> E/flutter ( 5966): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
> E/flutter ( 5966): <asynchronous suspension>
> E/flutter ( 5966): #1      SmsAutoFill.unregisterListener (package:sms_autofill/sms_autofill.dart:38:5)
> E/flutter ( 5966): <asynchronous suspension>
> E/flutter ( 5966):
