### ISSUE TITLE
Where is taking the phone hint from?

### ISSUE THREAD

**Issue by marcodecarolisidt** [jaumard/sms_autofill#74]
Hi, 
I'm using the phone hint, but receiving the number used from a previous phone.

So I updated the google account with the new phone number for autifill, and set it in the settings.
The package is still showing the old number.
Where is it taking it from?
Also what happens when there are no numbers?
Thanks

**Comment by jaumard** [comment]
Hello, phone numbers are retrieved with the following Android API https://developers.google.com/android/reference/com/google/android/gms/auth/api/credentials/HintRequest.Builder#setPhoneNumberIdentifierSupported(boolean)
