### ISSUE TITLE
Crash on flutter 1.22

### ISSUE THREAD

**Issue by haihai1993** [jaumard/sms_autofill#75]
Hi can you update flutterplugin for new version flutter because crash on flutter 1.22 when i add to project native android
<img width="1308" alt="Screen Shot 2021-01-13 at 12 42 15" src="https://user-images.githubusercontent.com/13572488/104411415-e464c300-559c-11eb-8f10-1d31089d73d8.png">

**Comment by grahamsmith** [comment]
This works for me on 1.22.5.

**Comment by jaumard** [comment]
Yep no problem on my side too with last flutter stable, try to do a flutter clean it should solve any weird issues.
