### ISSUE TITLE
OTP gets cleared when keyboard is dismissed!

### ISSUE THREAD

**Issue by Rudra370** [jaumard/sms_autofill#77]
The otp gets cleared when keyboard is dismissed and I'm also not able to fill the otp again with controller. Basically I'm not able to use controller to fill the otp.
Also, if I set current code then if I dismiss the keyboard it will start to fill the code from the starting when start to write again.

**Comment by vikalpnagar** [comment]
I was having a same problem. Try building your OTP text field in initState and store it in a variable. Use that variable in your widget tree.

**Comment by jaumard** [comment]
@vikalpnagar is right, if you loose your value it means your controller is a new one. You need to keep a reference to it during your widget lifecycle, statefullWidget, hook can do that for you.

**Comment by KonstantenKomkov** [comment]
I solved this adding custom formatter:
`class EndInputFormatter extends TextInputFormatter {
  @override
  TextEditingValue formatEditUpdate(
      TextEditingValue oldValue, TextEditingValue newValue) {
    if (newValue.text.isNotEmpty &&
        oldValue.text.length + 1 == newValue.text.length &&
        newValue.text.contains(oldValue.text) &&
        (newValue.text.indexOf(oldValue.text) == 1)) {
      final maskedValue = "${oldValue.text}${newValue.text.substring(0, 1)}";
      return TextEditingValue(
        selection: TextSelection.collapsed(offset: maskedValue.length),
        text: maskedValue,
      );
    }
    return newValue;
  }
}`

`inputFormatters: [
            FilteringTextInputFormatter.digitsOnly,
            EndInputFormatter(),
          ],`
