### ISSUE TITLE
How to resize UnderlineDecoration?

### ISSUE THREAD

**Issue by rrifafauzikomara** [jaumard/sms_autofill#9]
My code like this:

```
PinFieldAutoFill(
            keyboardType: TextInputType.phone,
            autofocus: true,
            codeLength: 4,
//            currentCode: _code,
            decoration: UnderlineDecoration(
              color: color_text_grey,
              textStyle: TextStyle(
                fontSize: MediaQuery.of(context).size.width / 10,
                color: color_text_black,
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
```

And the result like this:

<img width="450" alt="Screen Shot 2019-08-13 at 14 26 44" src="https://user-images.githubusercontent.com/26451363/62922772-6a903f00-bdd6-11e9-9601-c08fd1290f46.png">

How to resize property "UnderlineDecoration" ?

**Comment by jaumard** [comment]
Look like it's an issue you should ask here https://github.com/TinoGuo/pin_input_text_field as it's the package providing this decoration, I personally have no idea sorry
