### ISSUE TITLE
function getAppSignature can't run for release mode

### ISSUE THREAD

**Issue by radigi2207** [jaumard/sms_autofill#90]
Hi,
I am using this library to fill the OTP which works in most of the cases, but function getAppSignature can't run for release mode, the function return NULL, But when in debug mode it runs normally.

SmsAutoFill().getAppSignature.then((signature) {
  setState(() {
    appSignature = signature; // return NULL
  });
});
Version ^1.3.1
Device Testing 
* Version Android 10

Please help me with this. @jaumard

**Comment by psycura** [comment]
Same issue

**Comment by jaumard** [comment]
No one ?

**Comment by jaumard** [comment]
Closing then :)
