### ISSUE TITLE
NULL SAFETY

### ISSUE THREAD

**Issue by shinayser** [jaumard/sms_autofill#92]
Hello! Flutter 2.0 has been already released.
There is any ETA on when this project is getting a null safety version? 

Thanks!

**Comment by jaumard** [comment]
Not at all 😄 and it's not a priority to me. But I'll gladly review and merge a pr if someone is motivated to contribute

**Comment by grahamsmith** [comment]
I'll take a look next week although it will be my first time too. :)

**Comment by gagan-garcha** [comment]
Migrated the package.

**Comment by King-Korol** [comment]
When this packege will migrate to null safety?

**Comment by paulononaka** [comment]
@grahamsmith looks like it is missing to publish this new version in https://pub.dev/packages/sms_autofill.

**Comment by grahamsmith** [comment]
We have some final stuff to check over. When done we can publish.

**Comment by ShreyasMurali** [comment]
Hi, can i know when this would be published with new null safety version in pud.dev?
