### ISSUE TITLE
Add visible carret in PinFieldAutoFill

### ISSUE THREAD

**Issue by cedvdb** [jaumard/sms_autofill#94]
The carret is invisible in PinFieldAutoFill, which isn't good UI on the web since you cannot see if the field is focussed or not.

There should be an option to add it.

**Comment by jaumard** [comment]
I think you should open an issue on `pin_input_text_field` because it's this package who show the UI of this widget. Until it's done on it I'll not be able to do anything here

**Comment by cedvdb** [comment]
> I think you should open an issue on `pin_input_text_field` because it's this package who show the UI of this widget. Until it's done on it I'll not be able to do anything here

Apparently it's implemented since version 3.2.0

**Comment by jaumard** [comment]
ho good news then should be quite easy to add :D @grahamsmith might want this for the next version too then :)

**Comment by grahamsmith** [comment]
Agreed.

**Comment by jaumard** [comment]
Done on master, will be release soon in 2.0.0
