### ISSUE TITLE
Publish null safety to pub.dev

### ISSUE THREAD

**Issue by paulononaka** [jaumard/sms_autofill#95]
Looks like it is missing to publish this new version in https://pub.dev/packages/sms_autofill.

**Comment by zepedro123** [comment]
+1.
Dependency [pin_input_text_field](https://pub.dev/packages/pin_input_text_field) already supports null safety also. I think it's time to upgrade it too with urgency :) 
Thanks

**Comment by aeviou** [comment]
+1. 
GitHub code is up to date with null safety, should be a quick push to update pub.dev

**Comment by jaumard** [comment]
I've seen some problems around phone hints, it crash when native return null, we need to check that with @grahamsmith

**Comment by jaumard** [comment]
If you guys want to give it a try and give feedbacks please use master branch it's compatible with null safety

**Comment by grahamsmith** [comment]
I've got time this evening to take a look. The repo steps the better to help diagnose any issues.

**Comment by furaiev** [comment]
@jaumard please push at least with a prerelease suffix.

**Comment by kamyar75** [comment]
but not watching "null safety" banner in pub.dev

**Comment by jaumard** [comment]
2.0.0 was just released thanks for your patience

**Comment by kamyar75** [comment]
thanks
