### ISSUE TITLE
[PhoneFieldHint] The given phoneNumber is empty. Please set a non-empty phone number

### ISSUE THREAD

**Issue by zohaib304** [jaumard/sms_autofill#99]
PhoneFieldHint displays the phone number in the text field. but on submit firebase auth show exception. 

`Unhandled Exception: [firebase_auth/unknown] The given phoneNumber is empty. Please set a non-empty phone number with #setPhoneNumber()`

here is my `PhoneFieldHint`

```
PhoneFieldHint(
    controller: _phoneController,
    decoration: InputDecoration(
    fillColor: Color(0xffF5F7F9),
    filled: true,
    hintText: "+92 123 4567890",
    helperText: "Please enter your mobile number",
    border: InputBorder.none,
    focusedBorder: InputBorder.none,
    ),
),
```

**Comment by jaumard** [comment]
What append if before sending to firebase you print the value of `_phoneController ` ? because I see nothing wrong here, if value is on the field then it should be on _phoneController and if it is it mean you have a bug on your side.

**Comment by zohaib304** [comment]
value of `_phoneController' not printing on the console as well.

**Comment by zohaib304** [comment]
I just create a new project and still showing an empty string.

**Comment by afsar47** [comment]
you can add this line on your PhoneFieldHint Class
![Screen Shot 2021-04-10 at 4 57 01 AM 2](https://user-images.githubusercontent.com/13627028/114269052-7f611380-99b9-11eb-863b-337d4a7ab923.png)

**Comment by jaumard** [comment]
good catch @afsar47! Thanks!  It's fixed on master and will be release with null safety, closing for now
